# Generated by Django 3.0.8 on 2020-07-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_pins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pins',
            new_name='Pin',
        ),
    ]
